"""Fetch US 2021 life tables from CDC NVSR 72/12 Table 01.

Downloads the CDC-published Excel spreadsheet companion to NVSR Vol 72
No 12 (Arias & Xu, November 2023 — *United States Life Tables, 2021*)
once, caches it under `data/raw/cdc_nvsr/`, and writes qx values at
each age to `data/mortality.yaml`. The life-table anchor ages used by
the interpolator in `config.py` are a subset of the 0-100 table; this
script writes the exact CDC values at those anchors instead of the
previous hand-rounded approximations.

Previously, the values in `mortality.yaml` diverged from CDC 2021 Table 1
by 20-35% in the working-age range. A reproducibility referee flagged
this as a major issue; this script eliminates the drift.

Run via: `python -m whatnut.data_build.cdc_life_tables`
(add `--apply` to overwrite mortality.yaml).
"""

from __future__ import annotations

import sys
import urllib.request
from pathlib import Path

import openpyxl
import yaml

from whatnut.data_build import DATA_DIR, RAW_DIR

NVSR_URL = (
    "https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Publications/"
    "NVSR/72-12/Table01.xlsx"
)
NVSR_CACHE_DIR = RAW_DIR / "cdc_nvsr"
NVSR_CACHE = NVSR_CACHE_DIR / "Table01.xlsx"

# Anchor ages used by mortality.yaml. The config interpolator fills in
# single-year values between anchors in log space.
ANCHOR_AGES = [0, 1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60,
               65, 70, 75, 80, 85, 90, 95, 100]


def download_table01() -> Path:
    """Download the CDC NVSR 72-12 Table01.xlsx and cache it locally."""
    NVSR_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    if not NVSR_CACHE.exists():
        print(f"Downloading CDC Table01.xlsx from {NVSR_URL}")
        with urllib.request.urlopen(NVSR_URL) as r:
            NVSR_CACHE.write_bytes(r.read())
    return NVSR_CACHE


def parse_qx_by_age(path: Path) -> dict[int, float]:
    """Parse column B (qx) of the Table 1 sheet, keyed by start age."""
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb["Table 1"]
    qx_by_age: dict[int, float] = {}
    for row in ws.iter_rows(min_row=1, max_row=ws.max_row, values_only=True):
        age_cell, qx = row[0], row[1]
        if not isinstance(age_cell, str) or not isinstance(qx, (int, float)):
            continue
        label = age_cell.strip()
        # Formats: "0–1", "40–41", "100 and older"
        if label.startswith("100"):
            qx_by_age[100] = float(qx)
            continue
        dash = "–" if "–" in label else "-"
        head = label.split(dash, 1)[0].strip()
        if head.isdigit():
            qx_by_age[int(head)] = float(qx)
    return qx_by_age


def build_mortality_yaml(qx_all_ages: dict[int, float]) -> str:
    """Return the text of the new mortality.yaml (anchors only)."""
    rates = {a: round(qx_all_ages[a], 6) for a in ANCHOR_AGES if a in qx_all_ages}
    header = (
        "# US Life Table 2021 - mortality rates by age\n"
        "# Source: Arias E, Xu JQ. United States Life Tables, 2021.\n"
        "#   National Vital Statistics Reports, Vol 72, No 12.\n"
        "#   Hyattsville, MD: National Center for Health Statistics,\n"
        "#   November 2023.\n"
        "# https://www.cdc.gov/nchs/data/nvsr/nvsr72/nvsr72-12.pdf\n"
        "# Spreadsheet: https://ftp.cdc.gov/pub/Health_Statistics/NCHS/"
        "Publications/NVSR/72-12/Table01.xlsx\n"
        "# Raw download cached at data/raw/cdc_nvsr/Table01.xlsx.\n"
        "#\n"
        "# Values below are the exact qx entries from Table 1 at each\n"
        "# anchor age, regenerated by\n"
        "#   python -m whatnut.data_build.cdc_life_tables --apply\n"
        "# Intermediate ages are interpolated in log-space (Gompertz-like)\n"
        "# by src/whatnut/config.py.\n"
        "#\n"
        "# Format: age -> probability of dying in that year (qx)\n"
        "\nrates:\n"
    )
    # Fixed-point decimal so YAML parses numbers as floats (not strings).
    # Scientific notation like "9e-05" is ambiguous in YAML 1.1 and can
    # round-trip as a string under safe_load.
    body = "\n".join(f"  {a}: {rates[a]:.6f}" for a in sorted(rates))
    return header + body + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = argv or sys.argv[1:]
    path = download_table01()
    qx = parse_qx_by_age(path)
    print(f"Parsed {len(qx)} ages from CDC NVSR 72-12 Table 1")
    for a in [40, 50, 60, 70, 80]:
        print(f"  qx({a}) = {qx.get(a, 'missing'):.6f}")

    yaml_text = build_mortality_yaml(qx)
    out = DATA_DIR / "mortality.yaml"
    if "--apply" in argv:
        out.write_text(yaml_text)
        print(f"\nWrote {out}")
    else:
        print("\n--- preview of mortality.yaml ---")
        print(yaml_text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
