"""The manuscript is a template filled from frozen results, rendered with no kernel.

Integration checks run against the committed paper/index.qmd, paper/values.json
and paper/references.bib; unit checks pin down the fill, bibliography and
citation-check machinery with synthetic inputs.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
PAPER = ROOT / "paper"
sys.path.insert(0, str(PAPER))
sys.path.insert(0, str(ROOT / "scripts"))

import build_bib  # noqa: E402
import check_citations  # noqa: E402
import fill_paper  # noqa: E402
from fill_paper import FillError, Value  # noqa: E402

MINUS = "−"


def bib_keys() -> set[str]:
    return set(
        build_bib.bib_keys((PAPER / "references.bib").read_text(encoding="utf-8"))
    )


# --------------------------------------------------------------------------
# The committed manuscript
# --------------------------------------------------------------------------


def test_days_per_year_matches_results():
    """The formatters turn years into days with the pipeline's own constant."""
    results = json.loads((ROOT / "results" / "results.json").read_text("utf-8"))
    assert fill_paper.DAYS_PER_YEAR == results["meta"]["days_per_year"]


def test_fill_check_passes():
    """paper/index.qmd and values.json are exactly what template + results produce."""
    proc = subprocess.run(
        [sys.executable, "paper/fill_paper.py", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr


def test_filled_qmd_has_no_engine_cells_or_placeholders():
    text = (PAPER / "index.qmd").read_text(encoding="utf-8")
    assert "```{python" not in text
    assert "`{python}" not in text
    assert "{{" not in text
    assert fill_paper.problems_in_filled(text) == []
    assert text.startswith("---\n# GENERATED by paper/fill_paper.py")


def test_template_citations_exist_in_bib():
    cited = fill_paper.citation_keys(
        (PAPER / "index.qmd.in").read_text(encoding="utf-8")
    )
    assert cited, "the template cites nothing"
    missing = sorted(cited - bib_keys())
    assert not missing, f"cited but not in paper/references.bib: {missing}"


def test_template_figures_exist():
    template = (PAPER / "index.qmd.in").read_text(encoding="utf-8")
    assert fill_paper.missing_figures(template) == []


def test_values_json_is_sorted_scalars():
    raw = (PAPER / "values.json").read_text(encoding="utf-8")
    values = json.loads(raw)
    assert list(values) == sorted(values)
    for name, v in values.items():
        assert set(v) == {"kind", "raw", "text"}, name
        assert isinstance(v["raw"], (int, float, str)) and isinstance(v["text"], str), (
            name
        )
    # every printed value appears in the filled manuscript
    qmd = (PAPER / "index.qmd").read_text(encoding="utf-8")
    for name, v in values.items():
        assert v["text"] in qmd, f"{name} = {v['text']!r} is not in paper/index.qmd"


def test_references_bib_is_current():
    assert build_bib.build() == (PAPER / "references.bib").read_text(
        encoding="utf-8"
    ), "run python scripts/build_bib.py"


def test_quarto_config_renders_without_a_kernel():
    cfg = (PAPER / "_quarto.yml").read_text(encoding="utf-8")
    assert re.search(r"^execute:\n\s+enabled: false$", cfg, re.M)
    assert "jupyter" not in cfg
    assert "bibliography: references.bib" in cfg
    # KaTeX/MathJax need JavaScript, which the wrapper's sandboxed iframe blocks.
    assert "html-math-method: mathml" in cfg


def test_version_file():
    assert re.fullmatch(
        r"r\d+-\d{8}\n", (PAPER / "VERSION").read_text(encoding="utf-8")
    )


# --------------------------------------------------------------------------
# fill_paper machinery
# --------------------------------------------------------------------------

TEMPLATE = """---
title: "T"
---

Gain of {{a}} days, over {{b}} draws [@k].

{{table:t}}

: Caption {#tbl-t}
"""


def test_fill_substitutes_values_and_tables():
    out = fill_paper.fill(
        TEMPLATE,
        {"a": fill_paper.days(1.0), "b": fill_paper.integer(20000)},
        {"t": "| x |\n| - |\n| 1 |"},
    )
    assert "Gain of 365 days, over 20,000 draws" in out
    assert "| x |\n| - |\n| 1 |\n\n: Caption" in out
    assert out.startswith("---\n# GENERATED by paper/fill_paper.py")
    assert "{{" not in out


def test_fill_rejects_missing_value():
    with pytest.raises(FillError, match=r"\{\{b\}\} has no value \(line 5\)"):
        fill_paper.fill(TEMPLATE, {"a": fill_paper.days(1.0)}, {"t": "| x |"})


def test_fill_rejects_missing_table():
    with pytest.raises(FillError, match=r"table:t\}\} has no table"):
        fill_paper.fill(
            TEMPLATE, {"a": fill_paper.days(1.0), "b": fill_paper.integer(1)}, {}
        )


def test_fill_rejects_unused_value_and_table():
    values = {
        "a": fill_paper.days(1.0),
        "b": fill_paper.integer(1),
        "extra": fill_paper.integer(2),
    }
    with pytest.raises(FillError) as exc:
        fill_paper.fill(TEMPLATE, values, {"t": "| x |", "spare": "| y |"})
    assert "VALUES['extra'] is never used" in str(exc.value)
    assert "TABLES['spare'] is never used" in str(exc.value)


def test_fill_rejects_inline_table_placeholder():
    with pytest.raises(FillError, match="alone on its line"):
        fill_paper.fill("See {{table:t}} here.\n", {}, {"t": "| x |"})


def test_fill_leaves_no_malformed_placeholder_behind():
    out = fill_paper.fill("A {{ spaced }} one.\n", {}, {})
    assert fill_paper.problems_in_filled(out) == [
        "line 3: leftover '{{' (unfilled placeholder or shortcode)"
    ]


@pytest.mark.parametrize(
    "text, bad",
    [
        ("```{python}\nx = 1\n```\n", True),
        ("  ~~~{r}\nx\n~~~\n", True),
        ("Inline `{python} x` here.\n", True),
        ("{{< pagebreak >}}\n", True),
        ("```{=html}\n<br>\n```\n", False),
        ("```python\nx = 1\n```\n", False),
        ("```{.python}\nx = 1\n```\n", False),
        ("Math $\\frac{a}{b}$ and set $\\{x\\}$.\n", False),
    ],
)
def test_problems_in_filled(text, bad):
    assert bool(fill_paper.problems_in_filled(text)) is bad


def test_formatters():
    f = fill_paper
    assert f.days(1.0).text == "365"
    assert f.days(10.0).text == "3,653"  # 3,652.5 rounds half up
    assert f.days(-0.5).text == f"{MINUS}183"
    assert f.days(-0.0001).text == "0"  # never "-0"
    assert f.years(0.125).text == "0.13"  # half up, not half to even
    assert f.years(1234.5, 1).text == "1,234.5"
    assert f.dollars(1234.5).text == "$1,235"
    assert f.dollars(-5).text == f"{MINUS}$5"
    assert f.dollars(12.345, 2).text == "$12.35"
    assert f.pct(0.1234).text == "12%"
    assert f.pct(0.1234, 1).text == "12.3%"
    assert f.integer(20000).text == "20,000"
    assert f.integer(3.0).text == "3"
    assert f.ratio(0.775).text == "0.78"
    assert f.number(1234567.891, 1).text == "1,234,567.9"
    assert f.days(1.0) == Value(1.0, "days", "365")


def test_formatters_accept_numpy_scalars():
    np = pytest.importorskip("numpy")
    v = fill_paper.years(np.float64(0.456))
    assert v.text == "0.46" and type(v.raw) is float
    assert fill_paper.integer(np.int64(7)).raw == 7


@pytest.mark.parametrize("bad", [float("nan"), float("inf"), True, "1", None])
def test_formatters_reject_non_numbers(bad):
    with pytest.raises(FillError):
        fill_paper.years(bad)


def test_integer_rejects_fractions():
    with pytest.raises(FillError):
        fill_paper.integer(2.5)


def test_md_table():
    table = fill_paper.md_table(
        ["Nut", "Days"], [["Walnut", "12"], ["Almond", "9"]], "lr"
    )
    assert table.splitlines() == [
        "| Nut    | Days |",
        "| :----- | ---: |",
        "| Walnut | 12   |",
        "| Almond | 9    |",
    ]
    with pytest.raises(FillError):
        fill_paper.md_table(["a", "b"], [["1"]], "lr")


def test_values_json_rendering_is_sorted_and_stable():
    values = {"b": fill_paper.days(0.5), "a": fill_paper.integer(3)}
    out = fill_paper.render_values_json(values)
    assert out == fill_paper.render_values_json(dict(reversed(list(values.items()))))
    assert list(json.loads(out)) == ["a", "b"]
    assert out.endswith("}\n")


def test_citation_keys():
    text = (
        "---\nauthor: max@maxghenis.com\n---\n"
        "Cohorts [@aune2016nut; @ctt2010ldl, p. 3] and @delgobbo2015nuts showed it. "
        "See @fig-dose, @tbl-bracket, @sec-model and @eq-m. Mail max@maxghenis.com. "
        "Code `@decorator` and <!-- @hidden -->. Also [-@naghshi2021ala].\n"
    )
    assert fill_paper.citation_keys(text) == {
        "aune2016nut",
        "ctt2010ldl",
        "delgobbo2015nuts",
        "naghshi2021ala",
    }


def test_missing_figures(tmp_path):
    (tmp_path / "figures").mkdir()
    (tmp_path / "figures" / "a.png").write_bytes(b"png")
    text = "![A](figures/a.png){#fig-a}\n\n![B](figures/b.png)\n\n![C](https://example.org/c.png)\n"
    assert fill_paper.missing_figures(text, tmp_path) == ["line 3: figures/b.png"]


# --------------------------------------------------------------------------
# build_bib
# --------------------------------------------------------------------------


def test_bib_authors():
    assert (
        build_bib.bib_authors("Aune D, Fadnes LT", None) == "Aune, D. and Fadnes, L. T."
    )
    assert (
        build_bib.bib_authors("Del Gobbo LC, Mozaffarian D", None)
        == "{Del Gobbo}, L. C. and Mozaffarian, D."
    )
    assert build_bib.bib_authors(
        "Martínez-González MÁ; PREDIMED Study Investigators", None
    ) == ("Martínez-González, M. Á. and {PREDIMED Study Investigators}")
    assert build_bib.bib_authors(
        "Cholesterol Treatment Trialists' (CTT) Collaboration; Baigent C", None
    ) == ("{Cholesterol Treatment Trialists' (CTT) Collaboration} and Baigent, C.")
    assert (
        build_bib.bib_authors("Aune D, Keum N, et al", None)
        == "Aune, D. and Keum, N. and others"
    )
    assert build_bib.bib_authors("Rimm J-P", None) == "Rimm, J.-P."
    assert build_bib.bib_authors(None, "Aune") == "{Aune} and others"


def test_bib_escaping_and_pages():
    assert (
        build_bib.escape("Fruits & nuts: 5% of R_x") == r"Fruits \& nuts: 5\% of R\_x"
    )
    assert build_bib.bib_pages("1347–1356") == "1347--1356"
    assert build_bib.bib_pages("e34") == "e34"


def test_bib_authors_keeps_comma_organizations_whole():
    assert build_bib.bib_authors(
        "U.S. Department of Agriculture, Agricultural Research Service", None
    ) == ("{U.S. Department of Agriculture, Agricultural Research Service}")
    assert (
        build_bib.bib_authors("EFSA Panel (NDA); Turck D, Bohn T, et al.", None)
        == "{EFSA Panel (NDA)} and Turck, D. and Bohn, T. and others"
    )


def test_entry_type_inference():
    types = {"10.17226/9810": "edited-book", "10.1/art": "journal-article"}
    assert build_bib.entry_type("k", {"doi": "10.17226/9810"}, types) == "book"
    assert build_bib.entry_type("k", {"doi": "10.1/art"}, types) == "article"
    assert (
        build_bib.entry_type("k", {"doi": None, "url": "https://x"}, types) == "report"
    )  # a data table
    assert (
        build_bib.entry_type(
            "k", {"doi": None, "volume": "50", "pages": "454-460"}, types
        )
        == "article"
    )
    assert (
        build_bib.entry_type("k", {"doi": "10.1/art", "entry_type": "misc"}, types)
        == "misc"
    )
    with pytest.raises(build_bib.BibError):
        build_bib.entry_type("k", {"entry_type": "poster"}, types)
    book = build_bib.entry(
        "iom",
        dict(
            SOURCE,
            doi="10.17226/9810",
            journal="National Academies Press",
            volume=None,
            issue=None,
            pages=None,
        ),
        types,
    )
    assert (
        book.startswith("@book{iom,")
        and "publisher = {National Academies Press}" in book
    )


def _evidence(tmp_path, rows) -> Path:
    import yaml

    path = tmp_path / "evidence.yaml"
    path.write_text(yaml.safe_dump(rows, allow_unicode=True), encoding="utf-8")
    return path


SOURCE = {
    "key": "aune2016nut",
    "doi": "10.1186/s12916-016-0730-3",
    "first_author": "Aune",
    "authors": "Aune D, Keum N",
    "title": "Nut consumption and risk of cardiovascular disease",
    "journal": "BMC Medicine",
    "year": 2016,
    "volume": "14",
    "issue": "1",
    "pages": "207",
    "pmid": "27916000",
}


def test_build_bib_dedupes_and_is_deterministic(tmp_path):
    other = dict(
        SOURCE, key="zzz2020", doi="10.1/zzz", title="Another", authors="Zed A"
    )
    rows = [
        {"id": "r1", "source": SOURCE},
        {"id": "r2", "source": dict(SOURCE)},
        {"id": "r3", "source": other},
    ]
    bib = build_bib.build(_evidence(tmp_path, rows), tmp_path / "none.bib", tmp_path)
    assert build_bib.bib_keys(bib) == ["aune2016nut", "zzz2020"]
    assert "  number       = {1}," in bib and "  date         = {2016}," in bib
    assert (
        "  title        = {{Nut consumption and risk of cardiovascular disease}},"
        in bib
    )
    assert (
        build_bib.build(
            _evidence(tmp_path, list(reversed(rows))), tmp_path / "none.bib", tmp_path
        )
        == bib
    )


def test_build_bib_rejects_conflicting_rows(tmp_path):
    rows = [
        {"id": "r1", "source": SOURCE},
        {"id": "r2", "source": dict(SOURCE, year=2017)},
    ]
    with pytest.raises(build_bib.BibError, match="rows r1 and r2 disagree on year"):
        build_bib.build(_evidence(tmp_path, rows), tmp_path / "none.bib", tmp_path)


def test_build_bib_rejects_shared_doi(tmp_path):
    rows = [
        {"id": "r1", "source": SOURCE},
        {"id": "r2", "source": dict(SOURCE, key="aune_dup")},
    ]
    with pytest.raises(build_bib.BibError, match="claimed by keys"):
        build_bib.build(_evidence(tmp_path, rows), tmp_path / "none.bib", tmp_path)


def test_build_bib_merges_extra_and_rejects_collisions(tmp_path):
    ev = _evidence(tmp_path, [{"id": "r1", "source": SOURCE}])
    extra = tmp_path / "extra.bib"
    extra.write_text(
        "% note\n@report{nvsr2023,\n  title = {{US life tables, 2021}},\n}\n",
        encoding="utf-8",
    )
    assert build_bib.bib_keys(build_bib.build(ev, extra, tmp_path)) == [
        "aune2016nut",
        "nvsr2023",
    ]
    extra.write_text("@misc{aune2016nut,\n  title = {x},\n}\n", encoding="utf-8")
    with pytest.raises(build_bib.BibError, match="also come from evidence.yaml"):
        build_bib.build(ev, extra, tmp_path)


# --------------------------------------------------------------------------
# check_citations
# --------------------------------------------------------------------------


def test_title_similarity_normalizes():
    cr = "Dietary α‐Linolenic Acid, Marine ω‐3 Fatty Acids, and Mortality"
    local = "Dietary alpha-linolenic acid, marine omega-3 fatty acids, and mortality"
    assert check_citations.title_similarity(local, cr) == 1.0
    assert (
        check_citations.title_similarity(
            "Efectos del <i>café</i> &amp; té", "Efectos del cafe & te"
        )
        == 1.0
    )
    assert (
        check_citations.title_similarity(
            "{Nut consumption and mortality}", "Nut consumption and mortality"
        )
        == 1.0
    )
    assert (
        check_citations.title_similarity(
            "Nut consumption and mortality", "Olive oil consumption and mortality"
        )
        < 0.9
    )


def test_authors_match():
    assert check_citations.authors_match("Guasch-Ferré", "Guasch-Ferre")
    assert check_citations.authors_match("Sala-Vila", "Sala‐Vila")
    assert check_citations.authors_match(
        "Cholesterol Treatment Trialists' (CTT) Collaboration",
        "Cholesterol Treatment Trialists’ (CTT) Collaboration",
    )
    assert not check_citations.authors_match("Aune", "Keum")
    assert not check_citations.authors_match("Aune", None)


def test_bib_parse_roundtrip(tmp_path):
    ev = _evidence(
        tmp_path,
        [
            {
                "id": "r1",
                "source": dict(
                    SOURCE, authors="Del Gobbo LC, Aune D", first_author="Del Gobbo"
                ),
            }
        ],
    )
    bib = build_bib.build(ev, tmp_path / "none.bib", tmp_path)
    ((etype, key, fields),) = check_citations.parse_bib(bib)
    assert (etype, key) == ("article", "aune2016nut")
    assert fields["doi"] == SOURCE["doi"]
    assert check_citations.bib_first_author(fields["author"]) == "Del Gobbo"
    assert (
        check_citations.bib_first_author("{PREDIMED Investigators} and Ros, E.")
        == "PREDIMED Investigators"
    )
    assert check_citations.bib_first_author("Emilio Ros and others") == "Ros"
    assert (
        check_citations.bib_first_author(
            "{Panel on Dietary Antioxidants, IOM} and Ros, E."
        )
        == "Panel on Dietary Antioxidants, IOM"
    )


def _cache(
    tmp_path, title="Nut consumption and risk of cardiovascular disease", family="Aune"
) -> Path:
    cache = tmp_path / "crossref"
    cache.mkdir(exist_ok=True)
    record = {
        "DOI": SOURCE["doi"],
        "title": [title],
        "author": [{"family": family, "given": "D", "sequence": "first"}],
    }
    (cache / "10.1186_s12916-016-0730-3.json").write_text(
        json.dumps(record), encoding="utf-8"
    )
    (cache / "MANIFEST.json").write_text("{}", encoding="utf-8")
    return cache


def test_check_citations_offline_pass_and_fail(tmp_path, capsys):
    ev = _evidence(
        tmp_path,
        [
            {"id": "r1", "source": SOURCE},
            {
                "id": "r2",
                "source": {
                    "key": "usda2024fdc",
                    "title": "FoodData Central",
                    "authors": "US Department of Agriculture",
                    "year": 2024,
                },
            },
        ],
    )
    bib = tmp_path / "references.bib"
    bib.write_text(
        build_bib.build(ev, tmp_path / "none.bib", tmp_path), encoding="utf-8"
    )
    assert check_citations.run(True, ev, bib, _cache(tmp_path)) == 0
    assert "1 evidence rows have no DOI" in capsys.readouterr().out
    assert (
        check_citations.run(
            True, ev, bib, _cache(tmp_path, title="Something else entirely")
        )
        == 1
    )
    assert check_citations.run(True, ev, bib, _cache(tmp_path, family="Keum")) == 1
    empty = tmp_path / "empty"
    empty.mkdir()
    assert check_citations.run(True, ev, bib, empty) == 1
    assert "no cached Crossref record" in capsys.readouterr().out
