#!/usr/bin/env python3
"""Build paper/references.bib from data/evidence.yaml (plus paper/extra.bib).

One BibLaTeX entry per distinct ``source.key`` in the evidence rows, with
authors, title, journal, year, volume, number (issue), pages, DOI, PMID and
PMCID. Entries are sorted by key, and the output is byte-deterministic.
paper/extra.bib holds references the paper cites that are not evidence rows;
its entries are appended verbatim after the generated block.

Entry type: an explicit ``source.entry_type`` wins; otherwise the cached
Crossref record's type decides (journal-article -> @article, book types ->
@book with the ``journal`` field as publisher, report -> @report); a source with
no DOI and no volume, issue or pages (a data table, a guidance document) is a
@report with the ``journal`` field as institution; anything else is @article.

Fails loudly when two rows share a key but disagree on the source metadata,
when two keys claim the same DOI, or when an extra.bib key collides with an
evidence key.

    python scripts/build_bib.py           # write paper/references.bib
    python scripts/build_bib.py --check   # exit 1 if the committed file is stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
EVIDENCE = ROOT / "data" / "evidence.yaml"
EXTRA = ROOT / "paper" / "extra.bib"
CROSSREF_CACHE = ROOT / "data" / "sources" / "crossref"
OUT = ROOT / "paper" / "references.bib"

HEADER = """\
% GENERATED by scripts/build_bib.py from data/evidence.yaml and paper/extra.bib.
% Do not edit: change the evidence rows or paper/extra.bib and rerun.
"""

# Source fields that must agree across every row citing the same key.
IDENTITY_FIELDS = (
    "doi",
    "pmid",
    "pmcid",
    "first_author",
    "authors",
    "title",
    "journal",
    "year",
    "volume",
    "issue",
    "pages",
    "url",
    "entry_type",
)
ENTRY_TYPES = ("article", "book", "report", "misc", "online", "incollection")
BOOK_TYPES = {"book", "edited-book", "monograph", "reference-book"}


class BibError(RuntimeError):
    pass


# --------------------------------------------------------------------------
# Evidence -> source records
# --------------------------------------------------------------------------


def _norm_doi(doi: str | None) -> str | None:
    if not doi:
        return None
    doi = str(doi).strip()
    doi = re.sub(r"^(https?://(dx\.)?doi\.org/|doi:)", "", doi, flags=re.I)
    return doi


def load_sources(evidence_path: Path = EVIDENCE) -> dict[str, dict]:
    rows = yaml.safe_load(evidence_path.read_text(encoding="utf-8")) or []
    sources: dict[str, dict] = {}
    first_row: dict[str, str] = {}
    problems = []
    for row in rows:
        src = row.get("source") or {}
        key = src.get("key")
        rid = row.get("id", "?")
        if not key:
            problems.append(f"row {rid}: source.key missing")
            continue
        if key in sources:
            prev = sources[key]
            diff = [
                f for f in IDENTITY_FIELDS if _canon(prev.get(f)) != _canon(src.get(f))
            ]
            if diff:
                problems.append(
                    f"key {key}: rows {first_row[key]} and {rid} "
                    f"disagree on {', '.join(diff)}"
                )
            continue
        sources[key] = src
        first_row[key] = rid
    by_doi: dict[str, str] = {}
    for key, src in sorted(sources.items()):
        doi = _norm_doi(src.get("doi"))
        if doi:
            other = by_doi.setdefault(doi.lower(), key)
            if other != key:
                problems.append(f"DOI {doi} is claimed by keys {other} and {key}")
    if problems:
        raise BibError("evidence sources are inconsistent:\n  " + "\n  ".join(problems))
    return sources


def _canon(v):
    return None if v in (None, "") else str(v).strip()


# --------------------------------------------------------------------------
# Formatting
# --------------------------------------------------------------------------

ETAL = re.compile(r"^(et\s+al\.?|\.\.\.|…)$", re.I)


def bib_authors(authors: str | None, first_author: str | None) -> str:
    """'Aune D, Keum N, Del Gobbo LC; Org' -> 'Aune, D. and Keum, N. and ...'.

    Groups separated by ';' are split on ','. A name ending in capital initials
    is a person; anything else (a collaboration, a panel) is an organization and
    is braced so citeproc prints it whole. A trailing 'et al' or '...' becomes
    'and others'.
    """
    if not authors:
        if not first_author:
            raise BibError("source has neither authors nor first_author")
        return _org_or_person(first_author) + " and others"
    names = []
    others = False
    for group in authors.split(";"):
        org: list[str] = []  # consecutive non-person parts form one organization name
        for part in group.split(","):
            part = " ".join(part.split())
            if not part:
                continue
            if ETAL.match(part) or _person(part):
                if org:
                    names.append(_brace_org(", ".join(org)))
                    org = []
                if ETAL.match(part):
                    others = True
                else:
                    names.append(_person(part))
            else:
                org.append(part)
        if org:
            names.append(_brace_org(", ".join(org)))
    if not names:
        raise BibError(f"could not parse authors {authors!r}")
    return " and ".join(names + (["others"] if others else []))


def _vancouver_initials(token: str) -> bool:
    """'D', 'LT', 'MÁ', 'J-P': one to four capital letters, optionally hyphenated."""
    letters = token.replace("-", "")
    return (
        1 <= len(letters) <= 4
        and letters.isalpha()
        and letters.isupper()
        and not token.startswith("-")
    )


def _brace_org(name: str) -> str:
    return "{" + escape(name) + "}"


def _org_or_person(name: str) -> str:
    """A Vancouver person name ('Del Gobbo LC') or, failing that, an organization."""
    return _person(name) or _brace_org(name)


def _person(name: str) -> str | None:
    """'Del Gobbo LC' -> '{Del Gobbo}, L. C.'; None unless it ends in initials."""
    family, _, initials = name.rpartition(" ")
    if not family or not _vancouver_initials(initials):
        return None
    if "-" in initials:  # J-P -> J.-P.
        given = "-".join(
            " ".join(f"{c}." for c in part) for part in initials.split("-")
        )
    else:
        given = " ".join(f"{c}." for c in initials)
    # Brace multi-word family names so 'Del Gobbo' is not read as von + last.
    if " " in family:
        family = "{" + family + "}"
    return f"{escape(family)}, {given}"


def escape(s: str) -> str:
    """Escape the characters BibTeX/LaTeX treat specially; leave Unicode as UTF-8."""
    s = " ".join(str(s).split())
    return re.sub(r"(?<!\\)([&%$#_])", r"\\\1", s)


def bib_pages(pages) -> str:
    return re.sub(r"\s*[-–—]+\s*", "--", str(pages).strip())


def crossref_types(cache_dir: Path = CROSSREF_CACHE) -> dict[str, str]:
    """Lowercased DOI -> Crossref work type, from the cached records."""
    types = {}
    for f in sorted(cache_dir.glob("*.json")) if cache_dir.is_dir() else []:
        if f.name == "MANIFEST.json":
            continue
        msg = json.loads(f.read_text(encoding="utf-8"))
        msg = msg.get("message", msg)
        if msg.get("DOI") and msg.get("type"):
            types[msg["DOI"].lower()] = msg["type"]
    return types


def entry_type(key: str, src: dict, cr_types: dict[str, str]) -> str:
    explicit = src.get("entry_type")
    if explicit:
        if explicit not in ENTRY_TYPES:
            raise BibError(
                f"{key}: entry_type {explicit!r} is not one of {ENTRY_TYPES}"
            )
        return explicit
    doi = _norm_doi(src.get("doi"))
    cr = cr_types.get(doi.lower()) if doi else None
    if cr in BOOK_TYPES:
        return "book"
    if cr == "report":
        return "report"
    if (
        cr is None
        and not doi
        and not any(src.get(f) not in (None, "") for f in ("volume", "issue", "pages"))
    ):
        return "report"
    return "article"


# Where the source's `journal` field goes for each entry type.
CONTAINER_FIELD = {
    "article": "journaltitle",
    "book": "publisher",
    "report": "institution",
    "misc": "howpublished",
    "online": "organization",
    "incollection": "booktitle",
}


def entry(key: str, src: dict, cr_types: dict[str, str] | None = None) -> str:
    fields: list[tuple[str, str]] = []
    etype = entry_type(key, src, cr_types or {})
    fields.append(("author", bib_authors(src.get("authors"), src.get("first_author"))))
    if not src.get("title"):
        raise BibError(f"{key}: source.title missing")
    # Double braces keep the title's own capitalization through citeproc.
    fields.append(("title", "{" + escape(src["title"]) + "}"))
    if src.get("journal"):
        fields.append((CONTAINER_FIELD[etype], escape(src["journal"])))
    if not src.get("year"):
        raise BibError(f"{key}: source.year missing")
    fields.append(("date", str(src["year"])))
    if src.get("volume") not in (None, ""):
        fields.append(("volume", escape(src["volume"])))
    if src.get("issue") not in (None, ""):
        fields.append(("number", escape(src["issue"])))
    if src.get("pages") not in (None, ""):
        fields.append(("pages", bib_pages(src["pages"])))
    doi = _norm_doi(src.get("doi"))
    if doi:
        fields.append(("doi", doi))
    if src.get("pmid"):
        fields.append(("pmid", str(src["pmid"])))
    if src.get("pmcid"):
        fields.append(("pmcid", str(src["pmcid"])))
    if src.get("url") and not doi:
        fields.append(("url", str(src["url"])))
    width = max(len(name) for name, _ in fields)
    body = ",\n".join(f"  {name.ljust(width)} = {{{value}}}" for name, value in fields)
    return f"@{etype}{{{key},\n{body},\n}}\n"


BIB_KEY_RE = re.compile(r"^\s*@\s*(\w+)\s*\{\s*([^,\s]+)\s*,", re.M)


def bib_keys(bib_text: str) -> list[str]:
    """Entry keys in a .bib file (skips @comment, @string and @preamble)."""
    return [
        key
        for etype, key in BIB_KEY_RE.findall(bib_text)
        if etype.lower() not in ("comment", "string", "preamble")
    ]


def build(
    evidence_path: Path = EVIDENCE,
    extra_path: Path = EXTRA,
    cache_dir: Path = CROSSREF_CACHE,
) -> str:
    sources = load_sources(evidence_path)
    cr_types = crossref_types(cache_dir)
    parts = [HEADER]
    for key in sorted(sources):
        parts.append("\n" + entry(key, sources[key], cr_types))
    if extra_path.exists():
        extra = extra_path.read_text(encoding="utf-8")
        keys = bib_keys(extra)
        clash = sorted(set(keys) & set(sources))
        dup = sorted({k for k in keys if keys.count(k) > 1})
        if clash or dup:
            raise BibError(
                f"paper/extra.bib: keys {clash} also come from evidence.yaml; "
                f"duplicated keys {dup}"
            )
        if keys:
            parts.append(
                "\n% ---- paper/extra.bib (verbatim) ----\n\n" + extra.strip() + "\n"
            )
    return "".join(parts)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check", action="store_true", help="exit 1 if paper/references.bib is stale"
    )
    args = ap.parse_args(argv)
    try:
        bib = build()
    except BibError as exc:
        print(f"build_bib: {exc}", file=sys.stderr)
        return 1
    n = len(bib_keys(bib))
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != bib:
            print(
                "build_bib: paper/references.bib is stale; "
                "run python scripts/build_bib.py",
                file=sys.stderr,
            )
            return 1
        print(f"ok   paper/references.bib is current ({n} entries)")
        return 0
    OUT.write_text(bib, encoding="utf-8")
    print(f"wrote paper/references.bib ({n} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
