project:
  type: website
  output-dir: _build
  render:
    - index.qmd
    - appendix.qmd

website:
  title: "What Nut?"
  navbar: false
  page-navigation: true

execute:
  echo: false
  warning: false

format:
  html:
    theme:
      - cosmo
      - theme/brand.scss
    toc: true
    toc-depth: 3
    code-fold: true
    fig-cap-location: bottom
    format-links: false
    html-math-method: katex
    include-in-header:
      file: theme/chrome.html
    include-before-body:
      file: theme/header.html
    include-after-body:
      file: theme/footer.html
  pdf:
    documentclass: article
    pdf-engine: xelatex
    geometry:
      - margin=1in
    fig-cap-location: bottom
    toc: true
    toc-depth: 3
    number-sections: false

bibliography: references.bib
citeproc: true

author:
  - name: Max Ghenis
    email: max@maxghenis.com
