#!/usr/bin/env python3
"""Fill the manuscript template from the frozen results.

    paper/index.qmd.in  --(whatnut.results.r)-->  paper/index.qmd
                                                  paper/values.json

The template is the source of truth for prose. In it, ``{{name}}`` is replaced
by ``VALUES[name]`` and a line holding only ``{{table:name}}`` by
``TABLES[name]``. Every number the paper prints goes through one of the
formatters below, and values.json records each printed scalar next to the
unrounded number it came from, so any figure in the text traces back to
results/results.json.

The fill fails loudly when a placeholder has no value, when a value or table is
never used, when a figure link points at a missing file, and when the filled
text would contain an executable cell or a leftover ``{{``.

    python paper/fill_paper.py           # write paper/index.qmd and paper/values.json
    python paper/fill_paper.py --check   # regenerate in memory; exit 1 on a difference

To add numbers to the paper: write the prose with a new ``{{placeholder}}`` in
index.qmd.in, add the entry to the section builder it belongs to (one function
per section, below), and rerun. paper/index.qmd is generated; never edit it.
"""

from __future__ import annotations

import argparse
import difflib
import json
import math
import numbers
import re
import sys
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

PAPER = Path(__file__).resolve().parent
ROOT = PAPER.parent
TEMPLATE = PAPER / "index.qmd.in"
OUT_QMD = PAPER / "index.qmd"
OUT_VALUES = PAPER / "values.json"

GENERATED_NOTICE = (
    "GENERATED by paper/fill_paper.py from paper/index.qmd.in. "
    "Do not edit; edit the template."
)


class FillError(RuntimeError):
    """The template and the values do not line up. The message says where."""


# --------------------------------------------------------------------------
# Formatting: the only place a number becomes text.
# --------------------------------------------------------------------------

MINUS = "−"  # typographic minus for negative numbers

# Days per year used to express life-year gains in days. Julian year; load_r()
# refuses results.json when its meta.days_per_year differs.
DAYS_PER_YEAR = 365.25


@dataclass(frozen=True)
class Value:
    """One printed scalar: the number it came from, how it was formatted, the text."""

    raw: float | int | str
    kind: str
    text: str


def _py(x: float | int) -> float | int:
    """A plain int or float (numpy scalars too); rejects bools, NaN and infinities."""
    if isinstance(x, bool) or not isinstance(x, numbers.Real):
        raise FillError(f"expected a number, got {x!r}")
    if isinstance(x, numbers.Integral):
        return int(x)
    x = float(x)
    if not math.isfinite(x):
        raise FillError(f"cannot format non-finite number {x!r}")
    return x


def _decimal(x: float | int, ndigits: int) -> Decimal:
    """Round half away from zero (not Python's round-half-to-even)."""
    x = _py(x)
    quantum = Decimal(1).scaleb(-ndigits)
    return Decimal(repr(x) if isinstance(x, float) else x).quantize(
        quantum, rounding=ROUND_HALF_UP
    )


def _grouped(x: float | int, ndigits: int, prefix: str = "", suffix: str = "") -> str:
    """Fixed decimals, thousands separators, typographic minus; never prints -0."""
    d = _decimal(x, ndigits)
    body = f"{prefix}{abs(d):,.{ndigits}f}{suffix}"
    return MINUS + body if d < 0 else body


def number(x: float | int, ndigits: int = 2) -> Value:
    return Value(_py(x), f"number:{ndigits}", _grouped(x, ndigits))


def integer(n: int) -> Value:
    n = _py(n)
    if isinstance(n, float):
        if not n.is_integer():
            raise FillError(f"integer() got a non-integral value {n!r}")
        n = int(n)
    return Value(_py(n), "integer", _grouped(n, 0))


def days(years_value: float) -> Value:
    """A gain in years printed as whole days, e.g. 0.4521 -> '165'."""
    return Value(
        _py(years_value), "days", _grouped(_py(years_value) * DAYS_PER_YEAR, 0)
    )


def years(x: float, ndigits: int = 2) -> Value:
    return Value(_py(x), f"years:{ndigits}", _grouped(x, ndigits))


def dollars(x: float, ndigits: int = 0) -> Value:
    return Value(_py(x), f"dollars:{ndigits}", _grouped(x, ndigits, prefix="$"))


def pct(fraction: float, ndigits: int = 0) -> Value:
    """A fraction printed as a percentage, e.g. 0.123 -> '12%'."""
    return Value(
        _py(fraction),
        f"pct:{ndigits}",
        _grouped(_py(fraction) * 100, ndigits, suffix="%"),
    )


def ratio(x: float, ndigits: int = 2) -> Value:
    """Relative risks, ratios of risk ratios and similar, e.g. 0.78."""
    return Value(_py(x), f"ratio:{ndigits}", _grouped(x, ndigits))


def text(s: str) -> Value:
    return Value(s, "text", s)


def interval(lo: Value, hi: Value) -> str:
    """'a to b' for an interval whose ends are already formatted."""
    return f"{lo.text} to {hi.text}"


def md_table(header: list[str], rows: list[list[str]], align: str) -> str:
    """A pipe table. ``align`` has one of l/c/r per column."""
    ncol = len(header)
    if len(align) != ncol or any(len(row) != ncol for row in rows):
        raise FillError(
            f"table shape mismatch: header {ncol}, align {len(align)}, "
            f"rows {[len(r) for r in rows]}"
        )
    cells = [header, *rows]
    widths = [max(3, *(len(row[j]) for row in cells)) for j in range(ncol)]

    def rule(j: int) -> str:
        a, w = align[j], widths[j]
        if a == "l":
            return ":" + "-" * (w - 1)
        if a == "r":
            return "-" * (w - 1) + ":"
        if a == "c":
            return ":" + "-" * (w - 2) + ":"
        raise FillError(f"unknown alignment {a!r}")

    def line(row: list[str]) -> str:
        return "| " + " | ".join(c.ljust(widths[j]) for j, c in enumerate(row)) + " |"

    return "\n".join(
        [
            line(header),
            "| " + " | ".join(rule(j) for j in range(ncol)) + " |",
            *map(line, rows),
        ]
    )


# --------------------------------------------------------------------------
# VALUES and TABLES: one builder per section of the paper.
# --------------------------------------------------------------------------

SEXES = ("female", "male")

# Reference case: a US adult who starts at age 40 from no nuts and adds 28 g/day.
REF_AGE, REF_BACKGROUND, REF_DELTA = 40, 0, 28


def values_methods(r) -> dict[str, Value]:
    return {
        "mc_draws": integer(r.meta["n"]),
    }


def values_reference_case(r) -> dict[str, Value]:
    return {
        "ref_male_calibrated_mean_days": days(
            r.le_gain("male", REF_AGE, REF_DELTA, REF_BACKGROUND, "calibrated", "mean")
        ),
    }


def tables_reference_case(r) -> dict[str, str]:
    members = [("calibrated", "Calibrated"), ("face_value", "Face value")]
    rows = []
    for member, label in members:
        row = [label]
        for sex in SEXES:
            g = {
                s: days(r.le_gain(sex, REF_AGE, REF_DELTA, REF_BACKGROUND, member, s))
                for s in ("mean", "p10", "p90")
            }
            row.append(f"{g['mean'].text} ({interval(g['p10'], g['p90'])})")
        rows.append(row)
    return {
        "reference_bracket": md_table(
            ["Bracket member", "Women, days", "Men, days"], rows, "lrr"
        )
    }


VALUE_BUILDERS: tuple[Callable[..., dict[str, Value]], ...] = (
    values_methods,
    values_reference_case,
)
TABLE_BUILDERS: tuple[Callable[..., dict[str, str]], ...] = (tables_reference_case,)


def _merge(parts: Iterable[tuple[str, Mapping]]) -> dict:
    out: dict = {}
    for builder, part in parts:
        for name, v in part.items():
            if name in out:
                raise FillError(f"{builder} redefines {name!r}")
            out[name] = v
    return out


def build_values(r) -> dict[str, Value]:
    values = _merge((b.__name__, b(r)) for b in VALUE_BUILDERS)
    for name, v in values.items():
        if not NAME_RE.fullmatch(name):
            raise FillError(
                f"bad value name {name!r}: use lowercase letters, digits, underscores"
            )
        if not isinstance(v, Value):
            raise FillError(
                f"VALUES[{name!r}] is {type(v).__name__}; "
                "wrap it in a formatter (days, years, pct, ...)"
            )
    return values


def build_tables(r) -> dict[str, str]:
    tables = _merge((b.__name__, b(r)) for b in TABLE_BUILDERS)
    for name, t in tables.items():
        if not NAME_RE.fullmatch(name):
            raise FillError(f"bad table name {name!r}")
        if not isinstance(t, str) or not t.strip():
            raise FillError(f"TABLES[{name!r}] is empty or not a string")
        if "{{" in t:
            raise FillError(f"TABLES[{name!r}] contains '{{{{'")
    return tables


# --------------------------------------------------------------------------
# Template filling and validation.
# --------------------------------------------------------------------------

NAME_RE = re.compile(r"[a-z][a-z0-9_]*")
TABLE_LINE_RE = re.compile(r"^\{\{table:([a-z][a-z0-9_]*)\}\}[ \t]*$", re.M)
SCALAR_RE = re.compile(r"\{\{([a-z][a-z0-9_]*)\}\}")
ENGINE_CELL_RE = re.compile(
    r"^[ \t]*(`{3,}|~{3,})[ \t]*\{[ \t]*(?!=)[A-Za-z]", re.M
)  # ```{python}, not ```{=html}
INLINE_ENGINE_RE = re.compile(r"`\{[A-Za-z]+\}")  # `{python} x`, `{r} x`
FIGURE_RE = re.compile(r"!\[[^\]]*\]\(([^)\s]+)")


def _line_of(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def _where(text: str, pattern: re.Pattern, name: str) -> str:
    lines = sorted(
        {
            _line_of(text, m.start())
            for m in pattern.finditer(text)
            if m.group(1) == name
        }
    )
    return f"line {', '.join(map(str, lines))}"


def fill(template: str, values: Mapping[str, Value], tables: Mapping[str, str]) -> str:
    """Substitute values and tables; raise FillError on any mismatch."""
    stray = [
        m
        for m in re.finditer(r"\{\{table:", template)
        if not TABLE_LINE_RE.match(template, template.rfind("\n", 0, m.start()) + 1)
    ]
    if stray:
        lines = ", ".join(str(_line_of(template, m.start())) for m in stray)
        raise FillError(f"{{{{table:...}}}} must sit alone on its line (line {lines})")

    used_tables = set(TABLE_LINE_RE.findall(template))
    used_values = set(SCALAR_RE.findall(template))
    problems = []
    for name in sorted(used_values - set(values)):
        problems.append(
            f"placeholder {{{{{name}}}}} has no value "
            f"({_where(template, SCALAR_RE, name)})"
        )
    for name in sorted(used_tables - set(tables)):
        problems.append(
            f"placeholder {{{{table:{name}}}}} has no table "
            f"({_where(template, TABLE_LINE_RE, name)})"
        )
    for name in sorted(set(values) - used_values):
        problems.append(f"VALUES[{name!r}] is never used in the template")
    for name in sorted(set(tables) - used_tables):
        problems.append(f"TABLES[{name!r}] is never used in the template")
    if problems:
        raise FillError("template and values disagree:\n  " + "\n  ".join(problems))

    out = TABLE_LINE_RE.sub(lambda m: tables[m.group(1)], template)
    out = SCALAR_RE.sub(lambda m: values[m.group(1)].text, out)
    return _add_notice(out)


def _add_notice(text: str) -> str:
    if text.startswith("---\n"):
        return f"---\n# {GENERATED_NOTICE}\n{text[4:]}"
    return f"<!-- {GENERATED_NOTICE} -->\n\n{text}"


def problems_in_filled(text: str) -> list[str]:
    """What a filled manuscript must never contain. Empty list = clean."""
    found = []
    for m in ENGINE_CELL_RE.finditer(text):
        found.append(f"line {_line_of(text, m.start())}: executable code cell")
    for m in INLINE_ENGINE_RE.finditer(text):
        found.append(
            f"line {_line_of(text, m.start())}: inline executable code {m.group(0)!r}"
        )
    for m in re.finditer(r"\{\{", text):
        found.append(
            f"line {_line_of(text, m.start())}: "
            "leftover '{{' (unfilled placeholder or shortcode)"
        )
    return found


def missing_figures(text: str, base: Path = PAPER) -> list[str]:
    """Local image links whose file does not exist."""
    out = []
    for m in FIGURE_RE.finditer(text):
        target = m.group(1)
        if re.match(r"[a-z][a-z0-9+.-]*:", target):  # http:, data:, ...
            continue
        if not (base / target).is_file():
            out.append(f"line {_line_of(text, m.start())}: {target}")
    return out


# Pandoc citation keys: [@key], [@a; @b, p. 3], @key in running text, -@key.
# Cross-references (@fig-x, @tbl-x, @sec-x, @eq-x ...) and e-mail addresses are not
# citations.
CITE_RE = re.compile(
    r"(?<![A-Za-z0-9_.@\-])-?@([A-Za-z0-9_][A-Za-z0-9_:.#$%&+?<>~/\-]*)"
)
CROSSREF_PREFIXES = (
    "fig-",
    "tbl-",
    "sec-",
    "eq-",
    "lst-",
    "thm-",
    "lem-",
    "cor-",
    "prp-",
    "cnj-",
    "def-",
    "exm-",
    "exr-",
    "rem-",
    "sol-",
)


def citation_keys(text: str) -> set[str]:
    """Bibliography keys cited in a Quarto markdown document."""
    body = re.sub(r"\A---\n.*?\n---\n", "", text, flags=re.S)  # front matter
    body = re.sub(r"^(`{3,}|~{3,}).*?^\1", "", body, flags=re.S | re.M)  # fenced code
    body = re.sub(r"`[^`\n]*`", "", body)  # inline code
    body = re.sub(r"<!--.*?-->", "", body, flags=re.S)
    keys = set()
    for m in CITE_RE.finditer(body):
        key = m.group(1).rstrip(".:;,?")
        if key and not key.startswith(CROSSREF_PREFIXES):
            keys.add(key)
    return keys


# --------------------------------------------------------------------------
# Entry points.
# --------------------------------------------------------------------------


def load_r():
    """The results accessor. Runs r.verify() before any number is read."""
    sys.path.append(str(ROOT / "src"))  # after any installed or PYTHONPATH copy
    try:
        from whatnut.results import r
    except Exception as exc:  # missing results.json, stale package, ...
        raise FillError(
            f"cannot load whatnut.results ({type(exc).__name__}: {exc}); "
            "run python -m whatnut.pipeline first"
        ) from exc
    r.verify()
    if r.days_per_year != DAYS_PER_YEAR:
        raise FillError(
            f"results.json uses {r.days_per_year} days per year; the formatters "
            f"here use {DAYS_PER_YEAR}. Make them agree before printing days."
        )
    return r


def render_values_json(values: Mapping[str, Value]) -> str:
    payload = {
        name: {"kind": v.kind, "raw": v.raw, "text": v.text}
        for name, v in values.items()
    }
    return json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def generate(r=None, template_path: Path = TEMPLATE) -> tuple[str, str]:
    """(index.qmd text, values.json text), computed in memory."""
    r = load_r() if r is None else r
    values, tables = build_values(r), build_tables(r)
    qmd = fill(template_path.read_text(encoding="utf-8"), values, tables)
    problems = problems_in_filled(qmd) + [
        f"missing figure {p}" for p in missing_figures(qmd, template_path.parent)
    ]
    if problems:
        raise FillError("filled manuscript is not clean:\n  " + "\n  ".join(problems))
    return qmd, render_values_json(values)


def write(r=None) -> None:
    qmd, values_json = generate(r)
    OUT_QMD.write_text(qmd, encoding="utf-8")
    OUT_VALUES.write_text(values_json, encoding="utf-8")
    print(
        f"wrote {OUT_QMD.relative_to(ROOT)} and {OUT_VALUES.relative_to(ROOT)} "
        f"({len(json.loads(values_json))} values)"
    )


def check(r=None) -> int:
    qmd, values_json = generate(r)
    status = 0
    for path, fresh in ((OUT_QMD, qmd), (OUT_VALUES, values_json)):
        rel = path.relative_to(ROOT)
        if not path.exists():
            print(
                f"FAIL {rel} does not exist; run python paper/fill_paper.py",
                file=sys.stderr,
            )
            status = 1
            continue
        committed = path.read_text(encoding="utf-8")
        if committed != fresh:
            diff = difflib.unified_diff(
                committed.splitlines(),
                fresh.splitlines(),
                f"{rel} (committed)",
                f"{rel} (regenerated)",
                lineterm="",
            )
            print(f"FAIL {rel} is stale:", *list(diff)[:60], sep="\n", file=sys.stderr)
            status = 1
        else:
            print(f"ok   {rel} matches the template and results")
    return status


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and compare with the committed files",
    )
    args = ap.parse_args(argv)
    try:
        if args.check:
            return check()
        write()
        return 0
    except FillError as exc:
        print(f"fill_paper: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
