#!/usr/bin/env python3
"""Fill the manuscript template from the frozen results.

    paper/index.qmd.in  --(whatnut.results.r)-->  paper/index.qmd
                                                  paper/values.json

The template is the source of truth for prose. In it, ``{{name}}`` is replaced
by ``VALUES[name]`` and a line holding only ``{{table:name}}`` by
``TABLES[name]``. Every number the paper prints goes through one of the
formatters below, and values.json records each printed scalar next to the
unrounded number it came from, so any figure in the text traces back to
results/results.json.

The fill fails loudly when a placeholder has no value, when a value or table is
never used, when a figure link points at a missing file, and when the filled
text would contain an executable cell or a leftover ``{{``.

    python paper/fill_paper.py           # write paper/index.qmd and paper/values.json
    python paper/fill_paper.py --check   # regenerate in memory; exit 1 on a difference

To add numbers to the paper: write the prose with a new ``{{placeholder}}`` in
index.qmd.in, add the entry to the section builder it belongs to (one function
per section, below), and rerun. paper/index.qmd is generated; never edit it.
"""

from __future__ import annotations

import argparse
import difflib
import json
import math
import numbers
import re
import sys
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

PAPER = Path(__file__).resolve().parent
ROOT = PAPER.parent
TEMPLATE = PAPER / "index.qmd.in"
OUT_QMD = PAPER / "index.qmd"
OUT_VALUES = PAPER / "values.json"

GENERATED_NOTICE = (
    "GENERATED by paper/fill_paper.py from paper/index.qmd.in. "
    "Do not edit; edit the template."
)


class FillError(RuntimeError):
    """The template and the values do not line up. The message says where."""


# --------------------------------------------------------------------------
# Formatting: the only place a number becomes text.
# --------------------------------------------------------------------------

MINUS = "−"  # typographic minus for negative numbers

# Days per year used to express life-year gains in days. Julian year; load_r()
# refuses results.json when its meta.days_per_year differs.
DAYS_PER_YEAR = 365.25


@dataclass(frozen=True)
class Value:
    """One printed scalar: the number it came from, how it was formatted, the text."""

    raw: float | int | str
    kind: str
    text: str


def _py(x: float | int) -> float | int:
    """A plain int or float (numpy scalars too); rejects bools, NaN and infinities."""
    if isinstance(x, bool) or not isinstance(x, numbers.Real):
        raise FillError(f"expected a number, got {x!r}")
    if isinstance(x, numbers.Integral):
        return int(x)
    x = float(x)
    if not math.isfinite(x):
        raise FillError(f"cannot format non-finite number {x!r}")
    return x


def _decimal(x: float | int, ndigits: int) -> Decimal:
    """Round half away from zero (not Python's round-half-to-even)."""
    x = _py(x)
    quantum = Decimal(1).scaleb(-ndigits)
    return Decimal(repr(x) if isinstance(x, float) else x).quantize(
        quantum, rounding=ROUND_HALF_UP
    )


def _grouped(x: float | int, ndigits: int, prefix: str = "", suffix: str = "") -> str:
    """Fixed decimals, thousands separators, typographic minus; never prints -0."""
    d = _decimal(x, ndigits)
    body = f"{prefix}{abs(d):,.{ndigits}f}{suffix}"
    return MINUS + body if d < 0 else body


def number(x: float | int, ndigits: int = 2) -> Value:
    return Value(_py(x), f"number:{ndigits}", _grouped(x, ndigits))


def integer(n: int) -> Value:
    n = _py(n)
    if isinstance(n, float):
        if not n.is_integer():
            raise FillError(f"integer() got a non-integral value {n!r}")
        n = int(n)
    return Value(_py(n), "integer", _grouped(n, 0))


def days(years_value: float) -> Value:
    """A gain in years printed as whole days, e.g. 0.4521 -> '165'."""
    return Value(
        _py(years_value), "days", _grouped(_py(years_value) * DAYS_PER_YEAR, 0)
    )


def years(x: float, ndigits: int = 2) -> Value:
    return Value(_py(x), f"years:{ndigits}", _grouped(x, ndigits))


def dollars(x: float, ndigits: int = 0) -> Value:
    return Value(_py(x), f"dollars:{ndigits}", _grouped(x, ndigits, prefix="$"))


def pct(fraction: float, ndigits: int = 0) -> Value:
    """A fraction printed as a percentage, e.g. 0.123 -> '12%'."""
    return Value(
        _py(fraction),
        f"pct:{ndigits}",
        _grouped(_py(fraction) * 100, ndigits, suffix="%"),
    )


def ratio(x: float, ndigits: int = 2) -> Value:
    """Relative risks, ratios of risk ratios and similar, e.g. 0.78."""
    return Value(_py(x), f"ratio:{ndigits}", _grouped(x, ndigits))


def text(s: str) -> Value:
    return Value(s, "text", s)


def interval(lo: Value, hi: Value) -> str:
    """'a to b' for an interval whose ends are already formatted."""
    return f"{lo.text} to {hi.text}"


def md_table(header: list[str], rows: list[list[str]], align: str) -> str:
    """A pipe table. ``align`` has one of l/c/r per column."""
    ncol = len(header)
    if len(align) != ncol or any(len(row) != ncol for row in rows):
        raise FillError(
            f"table shape mismatch: header {ncol}, align {len(align)}, "
            f"rows {[len(r) for r in rows]}"
        )
    cells = [header, *rows]
    widths = [max(3, *(len(row[j]) for row in cells)) for j in range(ncol)]

    def rule(j: int) -> str:
        a, w = align[j], widths[j]
        if a == "l":
            return ":" + "-" * (w - 1)
        if a == "r":
            return "-" * (w - 1) + ":"
        if a == "c":
            return ":" + "-" * (w - 2) + ":"
        raise FillError(f"unknown alignment {a!r}")

    def line(row: list[str]) -> str:
        return "| " + " | ".join(c.ljust(widths[j]) for j, c in enumerate(row)) + " |"

    return "\n".join(
        [
            line(header),
            "| " + " | ".join(rule(j) for j in range(ncol)) + " |",
            *map(line, rows),
        ]
    )


# --------------------------------------------------------------------------
# VALUES and TABLES: one builder per section of the paper.
# --------------------------------------------------------------------------

SEXES = ("female", "male")
SEX_LABEL = {"female": "Women", "male": "Men"}

NUTS = (
    "walnut",
    "almond",
    "pistachio",
    "pecan",
    "hazelnut",
    "macadamia",
    "cashew",
    "peanut",
)
NUT_LABEL = {n: n for n in NUTS}
COMPOSITION_NUTS = NUTS + ("brazil_nut",)
NUMBER_WORDS = ("zero", "one", "two", "three", "four", "five", "six", "seven")
MONTHS = (
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
)
# The WAHA trial fed walnuts at 30 to 60 g/day (row rajaram2021_waha_walnut_ldl,
# exposure); the paper compares its LDL change with the short trials' per-gram
# effect at the middle of that range.
WAHA_MID_G = 45


def _data():
    from whatnut import data

    return data


def _row(row_id: str):
    return _data().row(row_id)


RATIO_MEASURES = ("RR", "HR", "OR", "RRR")


def _num(x: float, measure: str | None = "RR") -> str:
    """An evidence number printed as its source printed it: ratios keep at least
    two decimals, counts none, everything else its own decimals."""
    if measure in RATIO_MEASURES:
        return _grouped(x, max(2, _decimals(x)))
    if float(x).is_integer():
        return _grouped(x, 0)
    return _grouped(x, _decimals(x))


def _within_days(gap_days: float) -> Value:
    """'a day' or 'N days': the largest baseline gap, rounded up to whole days."""
    n = math.ceil(gap_days)
    return Value(gap_days, "days_ceil", "a day" if n == 1 else f"{n} days")


def _decimals(x: float) -> int:
    s = repr(float(x))
    if "e" in s:
        return 4
    frac = s.split(".")[1].rstrip("0") if "." in s else ""
    return len(frac)


def _row_decimals(row) -> int:
    """One decimal count for a row's estimate and interval (the most any prints)."""
    xs = [x for x in (row.estimate, row.ci_low, row.ci_high) if x is not None]
    return max(_decimals(x) for x in xs)


def _fmt_row(row, ndigits: int | None = None) -> Callable[[float], str]:
    if ndigits is not None:
        return lambda x: _grouped(x, ndigits)
    if row.measure in RATIO_MEASURES:
        return lambda x: _num(x, row.measure)
    nd = _row_decimals(row)
    return lambda x: _grouped(x, nd)


def ev(row_id: str, ndigits: int | None = None) -> Value:
    """An evidence estimate with its interval, e.g. '0.78 (95% CI 0.72 to 0.84)'."""
    r = _row(row_id)
    if r.estimate is None:
        raise FillError(f"evidence row {row_id} has no estimate")
    f = _fmt_row(r, ndigits)
    body = f(r.estimate)
    if r.ci_low is not None and r.ci_high is not None:
        level = int(round((r.ci_level or 0.95) * 100))
        body += f" ({level}% CI {f(r.ci_low)} to {f(r.ci_high)})"
    return Value(_py(r.estimate), "evidence", body)


def _stat_cell(stats: Mapping) -> str:
    g = {s: days(stats[s]) for s in ("mean", "p10", "p90")}
    return f"{g['mean'].text} ({interval(g['p10'], g['p90'])})"


def _range(lo: Value, hi: Value) -> Value:
    return Value(lo.raw, "range", f"{lo.text} to {hi.text}")


def _words(n: int) -> Value:
    return Value(n, "words", NUMBER_WORDS[n] if 0 <= n < len(NUMBER_WORDS) else str(n))


def _date(iso: str) -> str:
    y, m, d = iso.split("-")
    return f"{int(d)} {MONTHS[int(m) - 1]} {y}"


def _ref(r) -> tuple[int, float, float]:
    ref = r.reference
    return ref["a0"], ref["delta"], ref["background"]


def _price_extremes(r):
    by = r["cost"]["by_nut"]
    cheap = min(NUTS, key=lambda n: by[n]["usd_per_kg"])
    dear = max(NUTS, key=lambda n: by[n]["usd_per_kg"])
    return cheap, dear, by


def _label(r, member: str) -> str:
    return r.meta["scenario_labels"][member]


# ---- headline numbers (abstract and results) ---------------------------------


def values_headline(r) -> dict[str, Value]:
    a0, d, b = _ref(r)
    g = {
        (sex, mem): r.le_gain(sex, a0, d, b, mem)
        for sex in SEXES
        for mem in r.meta["main_members"]
    }
    face = g[("male", "face_value")]
    any_left = r["sensitivity"]["rows"]["curve_from_any"]["stats"]["male"]
    cheap, dear, by = _price_extremes(r)
    return {
        "m40_ldl_range": _range(
            days(g[("male", "ldl_chd")]), days(g[("male", "ldl_all")])
        ),
        "m40_cal": days(g[("male", "calibrated")]),
        "m40_calmort": days(g[("male", "calibrated_mortality")]),
        "m40_face": days(face),
        "m40_face_years": years(face, 1),
        "m40_ldl_weeks": number(g[("male", "ldl_all")] * DAYS_PER_YEAR / 7, 0),
        "f40_ldl_range": _range(
            days(g[("female", "ldl_chd")]), days(g[("female", "ldl_all")])
        ),
        "f40_cal": days(g[("female", "calibrated")]),
        "f40_face": days(g[("female", "face_value")]),
        "any_share": pct(1 - any_left["face_value"]["mean"] / face),
        "price_ratio": number(by[dear]["usd_per_kg"] / by[cheap]["usd_per_kg"], 0),
    }


# ---- evidence ---------------------------------------------------------------


def values_evidence(r) -> dict[str, Value]:
    data = _data()
    pts = {p["g"]: p["rr"] for p in data.aune_points("all_cause_mortality")}
    rr_min = min(pts.values())
    g_min = min(g for g, v in pts.items() if v == rr_min)
    if g_min != r.reference["delta"]:
        raise FillError(
            f"the text says the curve bottoms out at the reference dose; it bottoms "
            f"out at {g_min} g, the reference is {r.reference['delta']} g"
        )
    bop = data.bop_curve()
    bop_min = min(p["rr"] for p in bop)
    bop_row = _row("ihme_bop_nuts_seeds_ihd")
    bop_flat_g = min(p["g"] for p in bop if p["rr"] <= bop_min * (1 + 1e-3))
    stars = re.search(r"star rating (\d)", bop_row.notes or "", re.I)
    if not stars:
        raise FillError("ihme_bop_nuts_seeds_ihd notes carry no star rating")
    q2 = re.search(
        r"Q2 is ([\d.]+) to under ([\d.]+) g/day",
        _row("luu2015_shanghai_peanut_q2").exposure or "",
    )
    if not q2:
        raise FillError("luu2015_shanghai_peanut_q2 exposure names no Q2 range")
    rct_notes = " ".join((_row("delgobbo2015_ldl_per28g_rct").notes or "").split())
    dg = re.search(
        r"randomized trials fed a median ([\d.]+) g/day for a median ([\d.]+) weeks "
        r"\(all trials: ([\d.]+) g/day, range [\d-]+, and ([\d.]+) weeks",
        rct_notes,
    )
    if not dg:
        raise FillError("delgobbo2015_ldl_per28g_rct notes lack the trial medians")
    pred_pop = _row("predimed2018_nuts_all_cause_death").population or ""
    fu = re.search(r"median follow-up ([\d.]+) years", pred_pop)
    if not fu:
        raise FillError("predimed2018_nuts_all_cause_death names no median follow-up")
    phase = r.meta["phase_in_years"]
    pred_years = float(fu.group(1))
    # hazard ratio averaged over follow-up with a linear phase-in: the curve's
    # full log RR times the mean phase-in share over the trial's years
    phased = math.exp(math.log(rr_min) * min(1, pred_years / phase) / 2)
    ldl_rct = _row("delgobbo2015_ldl_per28g_rct")
    waha_implied = ldl_rct.estimate / ldl_rct.per_grams() * WAHA_MID_G
    return {
        "ev_aune_allcause": ev("aune2016_allcause_per28g"),
        "ev_aune_fu_short": ev("aune2016_allcause_fu_under10"),
        "ev_aune_fu_long": ev("aune2016_allcause_fu10plus"),
        "ev_aune_large": ev("aune2016_allcause_per28g_excl_small_studies"),
        "ev_liu2026": ev("liu2026_nutmeta_allcause"),
        "aune_rr_5g": ratio(pts[5.0]),
        "aune_rr_10g": ratio(pts[10.0]),
        "aune_rr_min": ratio(rr_min),
        "aune_min_g": integer(int(g_min)),
        "aune_rr_28g": ratio(pts[28.0]),
        "bop_rr_flat": ratio(bop_min, 3),
        "bop_flat_g": integer(int(round(bop_flat_g))),
        "bop_stars": text(NUMBER_WORDS[int(stars.group(1))]),
        "ev_golestan": ev("eslamparast2017_golestan"),
        "ev_luu_sccs": ev("luu2015_scc_shanghai"),
        "ev_luu_shanghai": ev("luu2015_shanghai_peanut_q5"),
        "luu_q2_range": text(f"{q2.group(1)} to {q2.group(2)}"),
        "ev_luu_shanghai_q2": ev("luu2015_shanghai_peanut_q2"),
        "ev_luu_pb": ev("luu2015_sccs_peanut_butter_q5"),
        "ev_gf_peanut": ev("guaschferre2017_peanut_cvd"),
        "ev_gf_treenut": ev("guaschferre2017_treenut_cvd"),
        "ev_gf_walnut": ev("guaschferre2017_walnut_cvd"),
        "ev_wang_salted": ev("wang2025_mr", 2),
        "delgobbo_dose_rct": text(dg.group(1)),
        "delgobbo_weeks_rct": text(dg.group(2)),
        "delgobbo_dose_all": text(dg.group(3)),
        "delgobbo_weeks_all": text(dg.group(4)),
        "ev_delgobbo_ldl_all": ev("delgobbo2015_ldl_per28g", 1),
        "ev_delgobbo_ldl_rct": ev("delgobbo2015_ldl_per28g_rct", 1),
        "ev_delgobbo_apob_rct": ev("delgobbo2015_apob_per28g_rct", 1),
        "predimed_nut_g": integer(int(_row("predimed2018_nut_mix").estimate)),
        "ev_predimed_nuts": ev("predimed2018_nuts_major_cvd"),
        "ev_predimed_evoo": ev("predimed2018_evoo_major_cvd"),
        "ev_predimed_stroke": ev("predimed2018_nuts_stroke"),
        "ev_predimed_death": ev("predimed2018_nuts_all_cause_death"),
        "ev_predimed_cvdeath": ev("predimed2018_nuts_cv_death"),
        "predimed_years": text(fu.group(1)),
        "predimed_phased_hr": ratio(phased),
        "ev_gf2013": ev("guaschferre2013_predimed_nut_frequency"),
        "ev_ctt_chd": ev("ctt2010_chd_death_per_mmol"),
        "ev_ctt_allcause": ev("ctt2010_all_cause_per_mmol"),
        "ev_silverman": ev("silverman2016_ldl_nonstatin"),
        "ev_waha": ev("rajaram2021_waha_walnut_ldl", 1),
        "waha_implied": number(waha_implied, 1),
    }


def values_calibration(r) -> dict[str, Value]:
    cal = r["calibration"]
    st = cal["strata"]
    a0, d, b = _ref(r)
    overall = _row("schwingshackl2021_rrr_overall")
    analog = st["calibrated_analog"]
    cs = [x["linear"]["c_point"] for x in st.values()]
    sens = r["sensitivity"]["calibrations"]
    return {
        "ev_schw_overall": ev("schwingshackl2021_rrr_overall"),
        "schw_overall_pi": text(
            f"{_num(overall.pi_low, 'RRR')} to {_num(overall.pi_high, 'RRR')}"
        ),
        "ev_schw_allcause": ev("schwingshackl2021_rrr_all_cause"),
        "ev_schw_intake": ev("schwingshackl2021_rrr_intake_vs_intake"),
        "schw_analog": Value(
            analog["rrr"],
            "pooled",
            f"{_grouped(analog['rrr'], 2)} (95% CI {_grouped(analog['rrr_ci'][0], 2)}"
            f" to {_grouped(analog['rrr_ci'][1], 2)})",
        ),
        "rr28_linear": ratio(cal["anchor_rr"]["linear"]),
        "rr28_curve": ratio(cal["anchor_rr"]["curve"]),
        "c_cal_point": pct(st["calibrated"]["linear"]["c_point"]),
        "c_calmort_point": pct(st["calibrated_mortality"]["linear"]["c_point"]),
        "c_min_point": pct(min(cs)),
        "c_max_point": pct(max(cs)),
        "harm_share_main": pct(st["calibrated"]["linear"]["share_draws_c_below_0"]),
        "harm_share_mort": pct(
            st["calibrated_mortality"]["linear"]["share_draws_c_below_0"]
        ),
        "m40_calmort_curve": days(
            sens["calibrated_mortality"]["curve"]["male"]["mean"]
        ),
    }


CALIBRATION_ROWS = (
    "calibrated_mortality",
    "calibrated_protective",
    "calibrated",
    "calibrated_analog",
    "calibrated_diet",
)


def tables_calibration(r) -> dict[str, str]:
    st = r["calibration"]["strata"]
    sens = r["sensitivity"]["calibrations"]
    rows = []
    for mem in CALIBRATION_ROWS:
        e = st[mem]
        n = (
            len(e["pair_rows"])
            if "pair_rows" in e
            else int(re.match(r"(\d+)", _row(e["row"]).population or "").group(1))
        )
        lo, hi = (_grouped(x, 2) for x in e["rrr_pi"])
        pi = f"{_grouped(e['rrr'], 2)} ({lo} to {hi})"
        rows.append(
            [
                _label(r, mem),
                str(n),
                pi,
                pct(e["linear"]["c_point"]).text,
                _stat_cell(sens[mem]["linear"]["male"]),
                pct(e["curve"]["c_point"]).text,
                _stat_cell(sens[mem]["curve"]["male"]),
            ]
        )
    header = [
        "Calibration",
        "Pairs",
        "Ratio (95% prediction interval)",
        "Share kept, linear anchor",
        "Days, linear anchor",
        "Share kept, curve anchor",
        "Days, curve anchor",
    ]
    return {"calibration": md_table(header, rows, "lrrrrrr")}


def tables_evidence(r) -> dict[str, str]:
    conv = r.meta["assumptions"]["ldl_mg_dl_per_mmol_l"]
    specs = [
        ("Tree nuts pooled, randomized trials", "delgobbo2015_ldl_per28g_rct"),
        ("Walnut", "guaschferre2018_walnut_ldl"),
        ("Almond", "leebravatti2019_almond_ldl"),
        ("Pistachio", "hadi2023_pistachio_ldl"),
        ("Pecan", "zhang2026_pecan_ldl"),
        ("Hazelnut", "perna2016_hazelnut_ldl"),
        ("Macadamia (one trial)", "jones2023_macadamia_ldl"),
        ("Cashew", "jalali2020_cashew_ldl"),
        ("Peanut", "jafariazad2020_peanut_ldl"),
    ]
    rows = []
    for label, rid in specs:
        row = _row(rid)
        scale = conv if (row.unit or "").startswith("mmol/L") else 1.0
        est = row.estimate * scale
        if row.ci_low is not None and row.ci_high is not None:
            level = int(round((row.ci_level or 0.95) * 100))
            kind = (
                "95% credible"
                if "HPD" in (row.notes or "")
                or "highest posterior" in (row.notes or "")
                else f"{level}% CI"
            )
            lo, hi = _grouped(row.ci_low * scale, 1), _grouped(row.ci_high * scale, 1)
            cell = f"{_grouped(est, 1)} ({kind} {lo} to {hi})"
        else:
            cell = f"{_grouped(est, 1)} (P = {_grouped(row.p_value(), 2)})"
        rows.append([label, cell, f"[@{row.source['key']}]"])
    return {"nut_ldl": md_table(["Nut", "LDL change, mg/dL", "Source"], rows, "lrl")}


# ---- model -----------------------------------------------------------------


def values_model(r) -> dict[str, Value]:
    data = _data()
    ala_lo, ala_hi = r["ala"]["support_g"]
    fad = {(row["sex"], row["start_age"]): row for row in r["fadnes"]["rows"]}
    main_age = r["fadnes"]["main_start_age"]
    old_age = max(age for _, age in fad)
    att = r.meta["assumptions"]["age_attenuation"]
    shares = data.cause_shares("male")
    ext35 = shares.external[shares.start.index(35)]
    weights = [
        w
        for w in data._read_csv(data.DATA / "composition" / "gram_weights.csv")
        if w["key"] == "almond" and "whole kernels" in w["description"]
    ]
    if len(weights) != 1:
        raise FillError("gram_weights.csv needs one almond 'whole kernels' weight")
    kernels = int(re.search(r"\((\d+) whole kernels\)", weights[0]["description"])[1])
    almond_g = float(weights[0]["grams"]) / kernels
    any_g = r.meta["assumptions"]["any_vs_none_g"]
    return {
        "phase_in_years": integer(r.meta["phase_in_years"]),
        "le_max_gap_days": _within_days(max(r["baseline_le"]["max_gap_days"].values())),
        "almonds_5g": integer(round(any_g / almond_g)),
        "ldl_conv": number(r.meta["assumptions"]["ldl_mg_dl_per_mmol_l"], 2),
        "mc_draws": integer(r.meta["n"]),
        "ev_naghshi": ev("naghshi2021_ala_all_cause_per_g"),
        "ev_naghshi_fixed": ev("naghshi2021_ala_all_cause_per_g_fixed"),
        "ala_lo": number(ala_lo, 2),
        "ala_hi": number(ala_hi, 1),
        "us_ala_m": number(_row("wweia_1720_ala_men").estimate, 2),
        "us_ala_f": number(_row("wweia_1720_ala_women").estimate, 2),
        "ext_share_m35": pct(ext35),
        "att_from": integer(att["from_age"]),
        "att_to": integer(att["to_age"]),
        "fadnes_rr": ratio(r["fadnes"]["inputs"]["hr"]),
        "repro_m20": years(fad[("male", main_age)]["ours"], 2),
        "fadnes_m20": years(fad[("male", main_age)]["theirs"], 1),
        "repro_f20": years(fad[("female", main_age)]["ours"], 2),
        "fadnes_f20": years(fad[("female", main_age)]["theirs"], 1),
        "repro_f80": years(fad[("female", old_age)]["ours"], 2),
        "fadnes_f80": years(fad[("female", old_age)]["theirs"], 1),
    }


# ---- results -----------------------------------------------------------------


def values_results(r) -> dict[str, Value]:
    a0, d, b = _ref(r)
    ages = r.meta["grid_axes"]["a0"]
    step = r.meta["assumptions"]["marginal_step_g"]
    dial = r.meta["assumptions"]["c_dial"]
    face = r.le_gain("male", a0, d, b, "face_value")
    out = {
        "dial_lo": number(dial[0], 1),
        "dial_mid": number(dial[1], 2),
        "m40_dial_lo": days(r.le_gain("male", a0, d, b, f"c_{dial[0]:g}")),
        "m40_dial_mid": days(r.le_gain("male", a0, d, b, f"c_{dial[1]:g}")),
        "age_young": integer(min(ages)),
        "age_old": integer(max(ages)),
        "share_5g": pct(r.le_gain("male", a0, 5, b, "face_value") / face),
        "share_10g": pct(r.le_gain("male", a0, 10, b, "face_value") / face),
        "marg_ldl_chd": days(r.le_gain("male", a0, step, 20, "ldl_chd")),
        "marg_ldl_all": days(r.le_gain("male", a0, step, 20, "ldl_all")),
        "us_nuts_g": number(
            _row("wweia_1720_nuts_seeds_adults").estimate
            * _row("fped_nut_oz_eq_grams").estimate,
            0,
        ),
    }
    for tag, mem in (("cal", "calibrated"), ("face", "face_value")):
        out[f"m_young_{tag}"] = days(r.le_gain("male", min(ages), d, b, mem))
        out[f"m_old_{tag}"] = days(r.le_gain("male", max(ages), d, b, mem))
        for bg in (0, 10, 20):
            out[f"marg_{tag}_b{bg}"] = days(r.le_gain("male", a0, step, bg, mem))
    return out


def tables_results(r) -> dict[str, str]:
    a0, _, b = _ref(r)
    deltas = r.reference["table_deltas"]
    header = ["Scenario"] + [
        f"{SEX_LABEL[sex]}, {dd} g" for dd in deltas for sex in SEXES
    ]
    rows = [
        [_label(r, mem)]
        + [
            _stat_cell(
                {s: r.le_gain(sex, a0, dd, b, mem, s) for s in ("mean", "p10", "p90")}
            )
            for dd in deltas
            for sex in SEXES
        ]
        for mem in r.meta["main_members"]
    ]
    return {"reference": md_table(header, rows, "l" + "r" * (len(header) - 1))}


def values_which_nut(r) -> dict[str, Value]:
    cheap, dear, by = _price_extremes(r)
    dates = sorted({dt for n in NUTS for dt in by[n]["price_dates"]})
    if len(dates) != 1:
        raise FillError(f"prices span several dates {dates}; say so in the text")
    sellers = [by[n]["n_retailers"] for n in NUTS]
    ala = r["ala"]["by_background"]
    w_avg, w_high = ala["average"]["walnut"], ala["high"]["walnut"]
    seeds = w_high["male"]["face_value:ala"]["increment"]["mean"]
    high_bg = r["ala"]["background_g"]["high"]["male"]
    return {
        "price_date": text(_date(dates[0])),
        "sellers_min": _words(min(sellers)),
        "sellers_max": _words(max(sellers)),
        "cheapest_price": dollars(by[cheap]["usd_per_kg"], 2),
        "cheapest_nut": text(NUT_LABEL[cheap] + "s"),
        "priciest_price": dollars(by[dear]["usd_per_kg"], 2),
        "priciest_nut": text(NUT_LABEL[dear] + "s"),
        "cpl_cheapest": dollars(
            by[cheap]["male"]["calibrated"]["usd_per_life_year"], 0
        ),
        "cpl_priciest": dollars(by[dear]["male"]["calibrated"]["usd_per_life_year"], 0),
        "cpl_cheapest_face": dollars(
            by[cheap]["male"]["face_value"]["usd_per_life_year"], 0
        ),
        "cpl_priciest_face": dollars(
            by[dear]["male"]["face_value"]["usd_per_life_year"], 0
        ),
        "walnut_ala": number(w_avg["nut_ala_g"], 2),
        "walnut_ala_counted_m": number(w_avg["male"]["counted_ala_g"], 2),
        "ala_premium_m": days(w_avg["male"]["face_value:ala"]["increment"]["mean"]),
        "ala_premium_m_fixed": days(
            w_avg["male"]["face_value:ala_fixed"]["increment"]["mean"]
        ),
        "ala_high_bg": number(high_bg, 0),
        "ala_premium_seeds": Value(
            seeds,
            "days_words",
            "nothing" if abs(seeds) < 1e-9 else days(seeds).text + " days",
        ),
        "ev_abdelhamid": ev("abdelhamid2020_ala_all_cause"),
    }


def values_sensitivity(r) -> dict[str, Value]:
    rows = r["sensitivity"]["rows"]
    main = rows["main"]["stats"]["male"]["face_value"]["mean"]

    def face(row_id: str) -> float:
        return rows[row_id]["stats"]["male"]["face_value"]["mean"]

    cs = r["sensitivity"]["curves_at_serving"]["curves"]
    b2021 = face("baseline_2021")
    return {
        "from_any_share": pct(face("curve_from_any") / main),
        "cvd_only_share": pct(r.le_gain("male", *_ref(r), "cvd_only") / main),
        "fu10_share": pct(face("rr_fu10") / main),
        "att_share": pct(face("attenuate_with_age") / main),
        "plateau_add": pct(face("curve_linear_plateau") / main - 1),
        "pchip28_face": days(cs["pchip_as_printed"]["male"]["face_value"]["mean"]),
        "main28_face": days(cs["main"]["male"]["face_value"]["mean"]),
        "baseline_2021_add": Value(
            b2021 - main, "days_delta", days(b2021 - main).text + " days"
        ),
    }


SENSITIVITY_TABLE = (
    ("main", "Main case"),
    ("curve_from_any", "Curve measured from 5 g (none to some not causal)"),
    ("curve_linear_plateau", "Linear per-28 g estimate with a plateau"),
    ("rr_fu10", "Cohorts followed ten years or more"),
    ("rr_large", "Without the five smallest studies"),
    ("exclude_external", "External causes of death left out"),
    ("attenuate_with_age", "Relative risk halves from 65 to 85"),
    ("phase_in_0", "No phase-in"),
    ("phase_in_20", "Phase-in over 20 years"),
    ("baseline_2021", "2021 life tables"),
    ("ldl_all_trials", "All 61 LDL trials, randomized or not"),
)
SENSITIVITY_COLUMNS = ("face_value", "calibrated", "ldl_all")


def tables_sensitivity(r) -> dict[str, str]:
    rows = []
    for rid, label in SENSITIVITY_TABLE:
        st = r["sensitivity"]["rows"][rid]["stats"]["male"]
        rows.append(
            [label]
            + [_stat_cell(st[c]) if c in st else "—" for c in SENSITIVITY_COLUMNS]
        )
    header = ["Choice"] + [_label(r, c) for c in SENSITIVITY_COLUMNS]
    return {"sensitivity": md_table(header, rows, "lrrr")}


# ---- practical notes -----------------------------------------------------------


def values_practical(r) -> dict[str, Value]:
    data = _data()
    comp = data.composition()
    pufa = {n: comp[n]["pufa_g"] for n in COMPOSITION_NUTS}
    if max(pufa, key=pufa.get) != "walnut":
        raise FillError(
            "the text says walnuts have the most PUFA; the data no longer agree"
        )
    kernel = [
        float(w["grams"])
        for w in data._read_csv(data.DATA / "composition" / "gram_weights.csv")
        if w["key"] == "brazil_nut" and w["modifier"] == "kernel"
    ]
    if len(kernel) != 1:
        raise FillError("gram_weights.csv needs exactly one Brazil nut kernel weight")
    se = _row("fdc_brazil_nut_selenium").estimate * kernel[0] / 100
    grams = 28
    return {
        "walnut_pufa": number(pufa["walnut"], 0),
        "flax_days": integer(int(_row("malcolmson2000_milled_flax_storage").estimate)),
        "roast_mda": integer(int(_row("schlormann2015_roasting").estimate)),
        "chia_milled": integer(int(_row("nieman2012_chia_milled_vs_whole").estimate)),
        "brazil_se_per_nut": number(se, 0),
        "efsa_se": integer(int(_row("efsa2023_selenium_ul").estimate)),
        "nasem_se": integer(int(_row("nasem2000_selenium_ul").estimate)),
        "ev_npc": ev("stranges2007_npc_diabetes"),
        "ev_select": ev("lippman2009_select_diabetes"),
        "kcal_walnut": number(comp["walnut"]["energy_kcal"] * grams / 100, 0),
        "kcal_almond": number(comp["almond"]["energy_kcal"] * grams / 100, 0),
        "discount_pct": pct(r["cost"]["discount_rate"]),
    }


def values_flip(r) -> dict[str, Value]:
    return {
        "ev_liu2020_change": ev("liu2020_nut_change_cvd"),
        "ev_liu2020_start": ev("liu2020_nut_start_cvd"),
    }


def values_reproduce(r) -> dict[str, Value]:
    version = (PAPER / "VERSION").read_text(encoding="utf-8").strip()
    return {"version": text(version)}


def tables_appendix(r) -> dict[str, str]:
    rows = []
    for rid in sorted(r.meta["evidence_rows"]):
        row = _row(rid)
        if row.estimate is None:
            est = "citation only"
        else:
            f = _fmt_row(row)
            est = f(row.estimate)
            if row.ci_low is not None and row.ci_high is not None:
                est += f" ({f(row.ci_low)} to {f(row.ci_high)})"
            if row.pi_low is not None and row.pi_high is not None:
                est += f"; PI {f(row.pi_low)} to {f(row.pi_high)}"
            if row.ci_low is None and row.pi_low is None:
                try:
                    est += f" (P = {_grouped(row.p_value(), 3)})"
                except Exception:
                    pass
        measure = " ".join(x for x in (row.measure, row.unit) if x and x != "value")
        checked = row.verified.get("value_checked_in") or "not stated"
        rows.append(
            [f"`{rid}`", measure or "value", est, f"[@{row.source['key']}]", checked]
        )
    return {
        "evidence": md_table(
            ["Row", "Measure", "Estimate (interval)", "Source", "Number checked in"],
            rows,
            "llrll",
        )
    }


VALUE_BUILDERS: tuple[Callable[..., dict[str, Value]], ...] = (
    values_headline,
    values_evidence,
    values_calibration,
    values_model,
    values_results,
    values_which_nut,
    values_sensitivity,
    values_practical,
    values_flip,
    values_reproduce,
)
TABLE_BUILDERS: tuple[Callable[..., dict[str, str]], ...] = (
    tables_evidence,
    tables_calibration,
    tables_results,
    tables_sensitivity,
    tables_appendix,
)


def _merge(parts: Iterable[tuple[str, Mapping]]) -> dict:
    out: dict = {}
    for builder, part in parts:
        for name, v in part.items():
            if name in out:
                raise FillError(f"{builder} redefines {name!r}")
            out[name] = v
    return out


def build_values(r) -> dict[str, Value]:
    values = _merge((b.__name__, b(r)) for b in VALUE_BUILDERS)
    for name, v in values.items():
        if not NAME_RE.fullmatch(name):
            raise FillError(
                f"bad value name {name!r}: use lowercase letters, digits, underscores"
            )
        if not isinstance(v, Value):
            raise FillError(
                f"VALUES[{name!r}] is {type(v).__name__}; "
                "wrap it in a formatter (days, years, pct, ...)"
            )
    return values


def build_tables(r) -> dict[str, str]:
    tables = _merge((b.__name__, b(r)) for b in TABLE_BUILDERS)
    for name, t in tables.items():
        if not NAME_RE.fullmatch(name):
            raise FillError(f"bad table name {name!r}")
        if not isinstance(t, str) or not t.strip():
            raise FillError(f"TABLES[{name!r}] is empty or not a string")
        if "{{" in t:
            raise FillError(f"TABLES[{name!r}] contains '{{{{'")
    return tables


# --------------------------------------------------------------------------
# Template filling and validation.
# --------------------------------------------------------------------------

NAME_RE = re.compile(r"[a-z][a-z0-9_]*")
TABLE_LINE_RE = re.compile(r"^\{\{table:([a-z][a-z0-9_]*)\}\}[ \t]*$", re.M)
SCALAR_RE = re.compile(r"\{\{([a-z][a-z0-9_]*)\}\}")
ENGINE_CELL_RE = re.compile(
    r"^[ \t]*(`{3,}|~{3,})[ \t]*\{[ \t]*(?!=)[A-Za-z]", re.M
)  # ```{python}, not ```{=html}
INLINE_ENGINE_RE = re.compile(r"`\{[A-Za-z]+\}")  # `{python} x`, `{r} x`
FIGURE_RE = re.compile(r"!\[[^\]]*\]\(([^)\s]+)")


def _line_of(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def _where(text: str, pattern: re.Pattern, name: str) -> str:
    lines = sorted(
        {
            _line_of(text, m.start())
            for m in pattern.finditer(text)
            if m.group(1) == name
        }
    )
    return f"line {', '.join(map(str, lines))}"


def fill(template: str, values: Mapping[str, Value], tables: Mapping[str, str]) -> str:
    """Substitute values and tables; raise FillError on any mismatch."""
    stray = [
        m
        for m in re.finditer(r"\{\{table:", template)
        if not TABLE_LINE_RE.match(template, template.rfind("\n", 0, m.start()) + 1)
    ]
    if stray:
        lines = ", ".join(str(_line_of(template, m.start())) for m in stray)
        raise FillError(f"{{{{table:...}}}} must sit alone on its line (line {lines})")

    used_tables = set(TABLE_LINE_RE.findall(template))
    used_values = set(SCALAR_RE.findall(template))
    problems = []
    for name in sorted(used_values - set(values)):
        problems.append(
            f"placeholder {{{{{name}}}}} has no value "
            f"({_where(template, SCALAR_RE, name)})"
        )
    for name in sorted(used_tables - set(tables)):
        problems.append(
            f"placeholder {{{{table:{name}}}}} has no table "
            f"({_where(template, TABLE_LINE_RE, name)})"
        )
    for name in sorted(set(values) - used_values):
        problems.append(f"VALUES[{name!r}] is never used in the template")
    for name in sorted(set(tables) - used_tables):
        problems.append(f"TABLES[{name!r}] is never used in the template")
    if problems:
        raise FillError("template and values disagree:\n  " + "\n  ".join(problems))

    out = TABLE_LINE_RE.sub(lambda m: tables[m.group(1)], template)
    out = SCALAR_RE.sub(lambda m: values[m.group(1)].text, out)
    return _add_notice(out)


def _add_notice(text: str) -> str:
    if text.startswith("---\n"):
        return f"---\n# {GENERATED_NOTICE}\n{text[4:]}"
    return f"<!-- {GENERATED_NOTICE} -->\n\n{text}"


def problems_in_filled(text: str) -> list[str]:
    """What a filled manuscript must never contain. Empty list = clean."""
    found = []
    for m in ENGINE_CELL_RE.finditer(text):
        found.append(f"line {_line_of(text, m.start())}: executable code cell")
    for m in INLINE_ENGINE_RE.finditer(text):
        found.append(
            f"line {_line_of(text, m.start())}: inline executable code {m.group(0)!r}"
        )
    for m in re.finditer(r"\{\{", text):
        found.append(
            f"line {_line_of(text, m.start())}: "
            "leftover '{{' (unfilled placeholder or shortcode)"
        )
    return found


def missing_figures(text: str, base: Path = PAPER) -> list[str]:
    """Local image links whose file does not exist."""
    out = []
    for m in FIGURE_RE.finditer(text):
        target = m.group(1)
        if re.match(r"[a-z][a-z0-9+.-]*:", target):  # http:, data:, ...
            continue
        if not (base / target).is_file():
            out.append(f"line {_line_of(text, m.start())}: {target}")
    return out


# Pandoc citation keys: [@key], [@a; @b, p. 3], @key in running text, -@key.
# Cross-references (@fig-x, @tbl-x, @sec-x, @eq-x ...) and e-mail addresses are not
# citations.
CITE_RE = re.compile(
    r"(?<![A-Za-z0-9_.@\-])-?@([A-Za-z0-9_][A-Za-z0-9_:.#$%&+?<>~/\-]*)"
)
CROSSREF_PREFIXES = (
    "fig-",
    "tbl-",
    "sec-",
    "eq-",
    "lst-",
    "thm-",
    "lem-",
    "cor-",
    "prp-",
    "cnj-",
    "def-",
    "exm-",
    "exr-",
    "rem-",
    "sol-",
)


def citation_keys(text: str) -> set[str]:
    """Bibliography keys cited in a Quarto markdown document."""
    body = re.sub(r"\A---\n.*?\n---\n", "", text, flags=re.S)  # front matter
    body = re.sub(r"^(`{3,}|~{3,}).*?^\1", "", body, flags=re.S | re.M)  # fenced code
    body = re.sub(r"`[^`\n]*`", "", body)  # inline code
    body = re.sub(r"<!--.*?-->", "", body, flags=re.S)
    keys = set()
    for m in CITE_RE.finditer(body):
        key = m.group(1).rstrip(".:;,?")
        if key and not key.startswith(CROSSREF_PREFIXES):
            keys.add(key)
    return keys


# --------------------------------------------------------------------------
# Entry points.
# --------------------------------------------------------------------------


def load_r():
    """The results accessor. Runs r.verify() before any number is read."""
    sys.path.append(str(ROOT / "src"))  # after any installed or PYTHONPATH copy
    try:
        from whatnut.results import r
    except Exception as exc:  # missing results.json, stale package, ...
        raise FillError(
            f"cannot load whatnut.results ({type(exc).__name__}: {exc}); "
            "run python -m whatnut.pipeline first"
        ) from exc
    r.verify()
    if r.days_per_year != DAYS_PER_YEAR:
        raise FillError(
            f"results.json uses {r.days_per_year} days per year; the formatters "
            f"here use {DAYS_PER_YEAR}. Make them agree before printing days."
        )
    return r


def render_values_json(values: Mapping[str, Value]) -> str:
    payload = {
        name: {"kind": v.kind, "raw": v.raw, "text": v.text}
        for name, v in values.items()
    }
    return json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def generate(r=None, template_path: Path = TEMPLATE) -> tuple[str, str]:
    """(index.qmd text, values.json text), computed in memory."""
    r = load_r() if r is None else r
    values, tables = build_values(r), build_tables(r)
    qmd = fill(template_path.read_text(encoding="utf-8"), values, tables)
    problems = problems_in_filled(qmd) + [
        f"missing figure {p}" for p in missing_figures(qmd, template_path.parent)
    ]
    if problems:
        raise FillError("filled manuscript is not clean:\n  " + "\n  ".join(problems))
    return qmd, render_values_json(values)


def write(r=None) -> None:
    qmd, values_json = generate(r)
    OUT_QMD.write_text(qmd, encoding="utf-8")
    OUT_VALUES.write_text(values_json, encoding="utf-8")
    print(
        f"wrote {OUT_QMD.relative_to(ROOT)} and {OUT_VALUES.relative_to(ROOT)} "
        f"({len(json.loads(values_json))} values)"
    )


def check(r=None) -> int:
    qmd, values_json = generate(r)
    status = 0
    for path, fresh in ((OUT_QMD, qmd), (OUT_VALUES, values_json)):
        rel = path.relative_to(ROOT)
        if not path.exists():
            print(
                f"FAIL {rel} does not exist; run python paper/fill_paper.py",
                file=sys.stderr,
            )
            status = 1
            continue
        committed = path.read_text(encoding="utf-8")
        if committed != fresh:
            diff = difflib.unified_diff(
                committed.splitlines(),
                fresh.splitlines(),
                f"{rel} (committed)",
                f"{rel} (regenerated)",
                lineterm="",
            )
            print(f"FAIL {rel} is stale:", *list(diff)[:60], sep="\n", file=sys.stderr)
            status = 1
        else:
            print(f"ok   {rel} matches the template and results")
    return status


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and compare with the committed files",
    )
    args = ap.parse_args(argv)
    try:
        if args.check:
            return check()
        write()
        return 0
    except FillError as exc:
        print(f"fill_paper: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
